config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    get "users", to: "devise/sessions#new"
  end
  resources :profiles
  resources :catches
  root 'home#index'
  get '/about', to: 'home#about'
  get '/winter', to: 'home#winter'
  get '/summer', to: 'home#summer'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/catch.rb
class Catch < ApplicationRecord
  belongs_to :profile
  broadcasts_to :profile
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
  has_many :catches

  def to_s
    "#{lastname} #{name}"
  end
end

app/models/user.rb
class User < ApplicationRecord
  extend Devise::Models
  devise :database_authenticatable,
         :registerable,
         :recoverable,
         :rememberable,
         :validatable

  after_create :create_profile
  has_one :profile

  private

  def create_profile
    profile = Profile.new
    profile.user_id = id
    profile.save
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/catches_controller.rb
# frozen_string_literal: true

class CatchesController < ApplicationController
  def index
    @catches = Catch.all
  end

  def show
    @catch = Catch.find(params[:id])
  end

  def new
    @catch = Catch.new
  end

  def create
    @catch = Catch.create(catch_params)
    @catch.profile = current_user.profile

    if @catch.valid? && @catch.save!
      respond_to do |format|
        format.turbo_stream
        format.html {render inline: "location.reload();" }
      end
    else
      redirect_to profile_path(current_user.profile)
    end
  end

  private

  def catch_params
    params.require(:catch).permit(
      :weight, :size, :name, :place, :date
    )
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index; end

  def about; end

  def summer; end

  def winter; end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  #сделать нормальынй поиск перед методами
  def show
    @profile = Profile.find_by(id: params[:id])
    if @profile.nil?
      render 'public/404'
    elsif @profile.user != current_user
      render 'public/403'
    else
      @profile
    end
  end

  def edit
    @profile = Profile.find(params[:id])
  end

  def update
    @profile = Profile.find(params[:id])
    @profile.name = profile_params[:name]
    @profile.lastname = profile_params[:lastname]
    @profile.save
    render 'show'
  end

  def profile_params
    params.require(:profile).permit(:name, :lastname)
  end
end

app/controllers/turbo_devise_controller.rb
class TurboDeviseController < ApplicationController
  class Responder < ActionController::Responder
    def to_turbo_stream
      controller.render(options.merge(formats: :html))
    rescue ActionView::MissingTemplate => error
      if get?
        raise error
      elsif has_errors? && default_action
        render rendering_options.merge(formats: :html, status: :unprocessable_entity)
      else
        redirect_to navigation_location
      end
    end
  end

  self.responder = Responder
  respond_to :html, :turbo_stream
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/catches/_catch.html.erb
<%=catch.created_at %>: <%=catch.name %> with weight <%=catch.weight %> kg
<br>

app/views/catches/create.turbo_stream.erb
<% # endpoint %>

app/views/catches/index.html.erb
<h2> Top catches </h2>

<%unless @catches.take.present? %>
  <p>No info</p>
<% else%>
  <h2>Top 5 catches by weight</h2>
  <table>
    <thead>
      <tr>
        <th>Name</th>
        <th>Weight</th>
        <th>Date</th>
        <th>Place</th>
        <th>Author</th>
      </tr>
    </thead>

    <tbody>
      <% @catches.order(weight: :desc).limit(5).each do |catch| %>
      <tr>
        <td><%=catch.name %></td>
        <td><%=catch.weight %></td>
        <td><%=catch.date %></td>
        <td><%=catch.place %></td>
        <td><%=catch.profile.to_s %></td>
      </tr>
      <%end %>

    </tbody>
  </table>
<%end %>

app/views/catches/new.html.erb
<%= turbo_frame_tag "new_catch" do %>
  <%= simple_form_for @catch,
                      remote: true,
                      data: { controller: "reset_form", action: "turbo:submit-end->reset_form#reset"} do |f| %>
    <%= f.input :name %>
    <%= f.input :weight %>
    <%= f.button :submit%>
  <% end %>
<% end %>

app/views/home/index.html.erb
<br>
<div class ="main-text">
    Fishing! Oh, how much has merged in this sound, isn't it? Fresh air, splashing water, forest silence, a fishing rod in
    hands, and then suddenly shouts: “Pecking! Pecking! Hook!" A surge of emotions, brutal adrenaline, frenzied excitement, happiness
    from capturing prey.

    Our favorite outdoor activity, a whole philosophy, cognitive science - that's what fishing is all about. For true
    connoisseurs of this activity, we have created our website about fishing. Here we will share with you all the secrets and
    the intricacies of fishing, we will tell you what, where and how to catch. Armed with our knowledge, you
    You will feel that you have become real professionals in your favorite business.
</div>

<div class="left-50">
    <%= image_tag('rybalka1.jpg')%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Fishmanv10</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <div class="navbar">
    <%= link_to 'Main', root_path %>
    <%if user_signed_in? %>
      <%= link_to 'Profile', profile_path(current_user.profile)%>
    <%end%>
    <%= link_to 'About', about_path %>
    <div class="dropdown">
      <button class="mainmenubtn">Fishing</button>
      <div class="dropdown-child">
        <%= link_to 'Winter', winter_path %>
        <%= link_to 'Summer', summer_path %>
      </div>
    </div>
    <div class="session-block">
      <% if user_signed_in? %>
        <%= link_to 'Sign out', destroy_user_session_path  %>
      <%else%>
        <%= link_to 'Sign up', new_user_registration_path %>
        <%= link_to 'Log in', new_user_session_path %>
      <%end%>
    </div>
  </div>

  <div class="main-content">

    <div id="logo">
      <%= image_tag('rybalka2.jpg')%>
    </div>

    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>
    <%= yield %>
    <p class="anime"> Buy a worm EXPENSIVELY  </p>
  </div>
  </body>
</html>

app/views/profiles/edit.html.erb
<h2> Edit Profile </h2>

<%= turbo_frame_tag @profile do %>
  <%= simple_form_for @profile do |f| %>
    <%= f.input :lastname%>
    <%= f.input :name %>
    <%= f.button :submit%>
  <%end%>
<% end %>

app/views/profiles/show.html.erb
<h2>Profile</h2>

<%= turbo_stream_from @profile  %>

<%= turbo_frame_tag @profile do %>
  <% unless @profile.name.nil? && @profile.lastname.nil? %>
    <p>Name: <%= @profile.name %></p>
    <p>Surname: <%= @profile.lastname %></p>
  <%end%>

  <%= link_to 'Edit profile info', edit_profile_path(@profile) %>
<% end %>

<br>
<hr>

<% if !@profile.name.nil?%>
  <div>
   <%= turbo_frame_tag "new_catch", src: new_catch_path(@profile) %>
  </div>
<% end %>

<div id="catches">
  <% unless @profile.name.nil? && @profile.lastname.nil? %>
    <div id="catches">
      <%= render @profile.catches %>
    </div>
  <%end%>
</div>